config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[create new edit index update]
  root 'users#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  validates :email, :username, :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to action: 'index'
    else
      render :new
    end
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
  end

  def edit
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReFormer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
    <%= f.label :username, 'Introduce your username' %><br />
    <%= f.text_field :username, placeholder: "Your username" %>

   <%= f.label :email, 'Introduce your email' %><br />
    <%= f.text_field :email , placeholder: "Your email" %>

    <%= f.label :password, 'Introduce your password' %><br />
    <%= f.password_field :password  , placeholder: "Your password"%>

    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1>Users</h1>
<%= link_to 'New User', new_user_path %>
<ul>
<% @users.each do | user | %>
<li><%=user.username  %>
 <%= link_to edit_user_path(user), class: "level-item" do %>
  <span>edit</span>
 <% end %>
</li>
<% end %>
</ul>

app/views/users/new.html.erb
<!-- <form action="/users" method="post">
  <label for="uname">Username:</label>
  <input type="text" id="username" name="user[username]"><br>
  <label for="email">Email:</label>
  <input type="text" id="email" name="user[email]"><br>
  <label for="pword">Password:</label>
  <input type="password" id="password" name="user[password]"><br>
  <input type="submit" value="Submit">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
</form>
-->
<!-- <%= form_for :user, :url => {:action => "create"}  do |f|  %>
     <%= f.label :username %><br />
     <%= f.text_field :username %>

    <%= f.label :email %><br />
     <%= f.text_field :email %>
  
     <%= f.label :password %><br />
     <%= f.password_field :password %>

     <%= f.submit %>
 <% end %> -->

<!-- 
<%= form_tag users_path do %>
       <%= label_tag 'user_username', 'username' %>
       <%= text_field_tag :'user[username]'%><br>

       <%= label_tag 'user_email', 'email' %>
       <%= text_field_tag :'user[email]'%><br>
       
       <%= label_tag 'user_password', 'password' %>
       <%= password_field_tag :'user[password]'%><br>
       <%= submit_tag %>
<% end %>
-->
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@user.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@user) do |f| %>
   <div>
     <%= f.label :username, 'Introduce your username' %><br />
 	<%= f.text_field :username, placeholder: "Your username" %>
   </div>
   <div>
    <%= f.label :email, 'Introduce your email' %><br />
       <%= f.text_field :email , placeholder: "Your email" %>
   </div>
   <div>
     <%= f.label :password, 'Introduce your password' %><br />
     <%= f.password_field :password  , placeholder: "Your password"%>
  </div>

     <%= f.submit %>
<% end %>